'use strict'

// Quantum-chemistry input files for every sampled configuration.
// Templates are plain text with {placeholders}; the Python engine (monet_qm.py)
// renders the same templates, sent by the client, with identical output.
;(function (root) {
  const BOHR = 0.529177210903 // Å

  // Standard atomic weights (IUPAC, abridged), used for Quantum ESPRESSO ATOMIC_SPECIES.
  const MASSES = {
    H: '1.008', He: '4.0026', Li: '6.94', Be: '9.0122', B: '10.81', C: '12.011', N: '14.007', O: '15.999',
    F: '18.998', Ne: '20.180', Na: '22.990', Mg: '24.305', Al: '26.982', Si: '28.085', P: '30.974', S: '32.06',
    Cl: '35.45', Ar: '39.95', K: '39.098', Ca: '40.078', Sc: '44.956', Ti: '47.867', V: '50.942', Cr: '51.996',
    Mn: '54.938', Fe: '55.845', Co: '58.933', Ni: '58.693', Cu: '63.546', Zn: '65.38', Ga: '69.723', Ge: '72.630',
    As: '74.922', Se: '78.971', Br: '79.904', Kr: '83.798', Rb: '85.468', Sr: '87.62', Y: '88.906', Zr: '91.224',
    Nb: '92.906', Mo: '95.95', Tc: '98', Ru: '101.07', Rh: '102.91', Pd: '106.42', Ag: '107.87', Cd: '112.41',
    In: '114.82', Sn: '118.71', Sb: '121.76', Te: '127.60', I: '126.90', Xe: '131.29', Cs: '132.91', Ba: '137.33',
    La: '138.91', Ce: '140.12', Pr: '140.91', Nd: '144.24', Pm: '145', Sm: '150.36', Eu: '151.96', Gd: '157.25',
    Tb: '158.93', Dy: '162.50', Ho: '164.93', Er: '167.26', Tm: '168.93', Yb: '173.05', Lu: '174.97', Hf: '178.49',
    Ta: '180.95', W: '183.84', Re: '186.21', Os: '190.23', Ir: '192.22', Pt: '195.08', Au: '196.97', Hg: '200.59',
    Tl: '204.38', Pb: '207.2', Bi: '208.98', Po: '209', At: '210', Rn: '222'
  }

  const STATES = { 1: ['sing', 's0', 'singlet'], 2: ['doub', 'd0', 'doublet'], 3: ['trip', 't0', 'triplet'], 4: ['quar', 'q0', 'quartet'], 5: ['quin', 'p0', 'quintet'] }

  const CODES = {
    gaussian: {
      label: 'Gaussian', folder: '', files: [{ name: '{tag}.dat', template:
`%nproc={nproc}
%chk={chk}
%mem={mem}
#p u{method}/{basis} maxdisk=300gb nosymm scf=tight gfinput gfoldprint pop=full

scf_{state}

{charge} {mult}
{coords}
` }]
    },
    orca: {
      label: 'ORCA', folder: 'orca', files: [{ name: '{tag}.inp', template:
`! UKS {method} {basis} TightSCF
%pal nprocs {nproc} end
%maxcore {maxcore}
# MONET configuration {index} (frame {frame}), {state}
* xyz {charge} {mult}
{coords}*
` }]
    },
    qbox: {
      label: 'Qbox', folder: 'qbox', files: [{ name: '{tag}.i', template:
`# Qbox input generated by MONET: configuration {index} (frame {frame}), {state}
# Units are bohr. {cell_note}
# Pseudopotential file names are placeholders; check net_charge/delta_spin conventions for your Qbox version.
set cell {qbox_cell}
{qbox_species}
{qbox_atoms}
set ecut 70
set xc PBE
set wf_dyn PSDA
set ecutprec 5
set net_charge {charge}
set nspin {nspin}
set delta_spin {delta_spin}
randomize_wf
run 0 200 10
save {tag}_conf{index}.xml
` }]
    },
    qe: {
      label: 'Quantum ESPRESSO (pw.x)', folder: 'qe', files: [{ name: '{tag}.pwi', template:
`! MONET configuration {index} (frame {frame}), {state}. {cell_note}
&CONTROL
  calculation = 'scf'
  prefix = '{tag}_conf{index}'
  pseudo_dir = './pseudo'
  outdir = './tmp'
/
&SYSTEM
  ibrav = 0
  nat = {nat}
  ntyp = {ntyp}
  ecutwfc = 50
  tot_charge = {charge}
  nspin = {nspin}
{qe_magnetization}/
&ELECTRONS
  conv_thr = 1.0d-8
/
ATOMIC_SPECIES
{qe_species}
CELL_PARAMETERS angstrom
{cell_ang}
ATOMIC_POSITIONS angstrom
{coords}
K_POINTS gamma
` }]
    },
    vasp: {
      label: 'VASP', folder: 'vasp', files: [
        { name: 'POSCAR', template:
`MONET configuration {index} (frame {frame}); atoms grouped by element
1.0
{cell_ang}
{vasp_species}
{vasp_counts}
Cartesian
{vasp_coords}
` },
        { name: 'INCAR_{tag}', template:
`SYSTEM = MONET configuration {index} {state}
# {cell_note}
# Net charge {charge}: set NELECT accordingly for charged systems.
ENCUT = 500
ISPIN = {nspin}
NUPDOWN = {unpaired}
ISMEAR = 0
SIGMA = 0.01
EDIFF = 1E-6
` }]
    },
    cp2k: {
      label: 'CP2K', folder: 'cp2k', files: [{ name: '{tag}.inp', template:
`! MONET configuration {index} (frame {frame}), {state}. {cell_note}
&GLOBAL
  PROJECT {tag}_conf{index}
  RUN_TYPE ENERGY
&END GLOBAL
&FORCE_EVAL
  METHOD Quickstep
  &DFT
    BASIS_SET_FILE_NAME BASIS_MOLOPT
    POTENTIAL_FILE_NAME GTH_POTENTIALS
    CHARGE {charge}
    MULTIPLICITY {mult}
    UKS {uks}
    &MGRID
      CUTOFF 400
    &END MGRID
    &XC
      &XC_FUNCTIONAL PBE
      &END XC_FUNCTIONAL
    &END XC
  &END DFT
  &SUBSYS
    &CELL
{cp2k_cell}
      PERIODIC XYZ
    &END CELL
    &COORD
{coords}    &END COORD
{cp2k_kinds}
  &END SUBSYS
&END FORCE_EVAL
` }]
    }
  }

  const PARAMETERS = { charge: 0, multiplicities: [1, 3], nproc: 6, mem: '4gb', method: 'b3lyp', basis: '6-31+g(d,p)', padding: 10 }

  // Spec sent to both engines. `codes` maps code -> editable file templates.
  function defaultSpec (codes = ['gaussian']) {
    return {
      codes: Object.fromEntries(codes.map(code => [code, { folder: CODES[code].folder, files: CODES[code].files.map(file => ({ ...file })) }])),
      params: { ...PARAMETERS, multiplicities: [...PARAMETERS.multiplicities] },
      masses: MASSES,
      cell: null
    }
  }

  const num = value => String(value)
  const fixed = (value, digits) => (value + 0).toFixed(digits)

  function memoryMB (text) {
    const match = /^\s*(\d+(?:\.\d+)?)\s*(gb|mb|g|m)?\s*$/i.exec(String(text))
    if (!match) return 4000
    return Number(match[1]) * (/^g/i.test(match[2] || 'gb') ? 1000 : 1)
  }

  function stateOf (mult) {
    const [tag, chk, state] = STATES[mult] || [`mult${mult}`, `m${mult}`, `multiplicity-${mult}`]
    return { tag, chk: `${chk}.chk`, state }
  }

  // Cell rows in Å: manual/source lattice, or an orthorhombic box with vacuum padding.
  function cellFor (conf, spec) {
    const lattice = spec.cell || conf.lattice
    if (lattice) return { rows: lattice, note: spec.cell ? 'Cell: applied manual cell.' : 'Cell: from the trajectory.' }
    const pad = Number(spec.params.padding)
    const rows = [0, 1, 2].map(axis => {
      let low = Infinity, high = -Infinity
      for (const p of conf.positions) { low = Math.min(low, p[axis]); high = Math.max(high, p[axis]) }
      const row = [0, 0, 0]
      row[axis] = Math.max(high - low + pad, 1)
      return row
    })
    return { rows, note: `Cell: orthorhombic box = extent + ${num(pad)} A padding (no cell in the trajectory).` }
  }

  function context (conf, spec, mult) {
    const p = spec.params
    const symbols = conf.symbols
    const positions = conf.positions
    const species = [...new Set(symbols)]
    const cell = cellFor(conf, spec)
    const unpaired = mult - 1
    const coords = symbols.map((s, i) => `${s}  ${fixed(positions[i][0], 7)}  ${fixed(positions[i][1], 7)}  ${fixed(positions[i][2], 7)}\n`).join('')
    const counts = species.map(s => symbols.filter(x => x === s).length)
    const order = species.flatMap(s => symbols.map((x, i) => x === s ? i : -1).filter(i => i >= 0))
    const seen = {}
    return {
      ...stateOf(mult),
      index: num(conf.index), frame: num(conf.frame), charge: num(p.charge), mult: num(mult),
      nproc: num(p.nproc), mem: String(p.mem), method: String(p.method), basis: String(p.basis),
      maxcore: num(Math.floor(memoryMB(p.mem) / Math.max(1, Number(p.nproc)))),
      coords, nat: num(symbols.length), ntyp: num(species.length),
      nspin: unpaired ? '2' : '1', unpaired: num(unpaired), delta_spin: num(unpaired / 2),
      uks: unpaired ? '.TRUE.' : '.FALSE.',
      cell_note: cell.note,
      cell_ang: cell.rows.map(row => row.map(v => fixed(v, 10)).join('  ')).join('\n'),
      qbox_cell: cell.rows.flat().map(v => fixed(v / BOHR, 8)).join(' '),
      qbox_species: species.map(s => `species ${s.toLowerCase()} ${s}_ONCV_PBE-1.0.xml`).join('\n'),
      qbox_atoms: symbols.map((s, i) => {
        seen[s] = (seen[s] || 0) + 1
        return `atom ${s}${seen[s]} ${s.toLowerCase()} ${positions[i].map(v => fixed(v / BOHR, 8)).join(' ')}`
      }).join('\n'),
      qe_species: species.map(s => `  ${s} ${spec.masses[s] || '1.0'} ${s}.UPF`).join('\n'),
      qe_magnetization: unpaired ? `  tot_magnetization = ${unpaired}\n` : '',
      vasp_species: species.join(' '),
      vasp_counts: counts.join(' '),
      vasp_coords: order.map(i => positions[i].map(v => fixed(v, 10)).join('  ')).join('\n'),
      cp2k_cell: ['A', 'B', 'C'].map((axis, k) => `      ${axis} ${cell.rows[k].map(v => fixed(v, 10)).join(' ')}`).join('\n'),
      cp2k_kinds: species.map(s => `    &KIND ${s}\n      BASIS_SET DZVP-MOLOPT-SR-GTH\n      POTENTIAL GTH-PBE\n    &END KIND`).join('\n')
    }
  }

  const fill = (text, values) => text.replace(/\{(\w+)\}/g, (match, key) => Object.prototype.hasOwnProperty.call(values, key) ? values[key] : match)

  function validate (spec) {
    const p = spec.params || {}
    const mults = p.multiplicities
    if (!Array.isArray(mults) || !mults.length || mults.some(m => !Number.isInteger(m) || m < 1 || m > 11) || new Set(mults).size !== mults.length) {
      throw new Error('Enter distinct spin multiplicities between 1 and 11, e.g. "1 3".')
    }
    if (!Number.isInteger(p.charge) || Math.abs(p.charge) > 50) throw new Error('Charge must be an integer.')
    if (!Number.isInteger(p.nproc) || p.nproc < 1) throw new Error('Processors must be a positive integer.')
    if (!Number.isFinite(p.padding) || p.padding < 0) throw new Error('Vacuum padding must be zero or positive.')
    for (const code of Object.keys(spec.codes || {})) {
      if (!CODES[code]) throw new Error(`Unknown input code ${code}.`)
      for (const file of spec.codes[code].files) {
        if (!/^[A-Za-z0-9_.{}-]+$/.test(file.name)) throw new Error(`Invalid file name pattern ${file.name}.`)
      }
    }
    return spec
  }

  // conf = { index (1-based), frame, symbols, positions: [[x,y,z]...], lattice?: 3x3 }
  function render (spec, conf) {
    const out = []
    for (const [code, entry] of Object.entries(spec.codes)) {
      for (const file of entry.files) {
        const perState = /\{(tag|mult|state|chk)\}/.test(file.name)
        for (const mult of perState ? spec.params.multiplicities : [spec.params.multiplicities[0]]) {
          const values = context(conf, spec, mult)
          const name = fill(file.name, values)
          const folder = CODES[code].folder
          out.push({ path: folder ? `${folder}/${name}` : name, text: fill(file.template, values) })
        }
      }
    }
    return out
  }

  const api = { CODES, MASSES, PARAMETERS, BOHR, defaultSpec, render, validate, stateOf }
  if (typeof module === 'object' && module.exports) module.exports = api
  else root.MonetQM = api
})(globalThis)
